### ISSUE TITLE
get_storage_key function is under graph client and should be under identity client?

### ISSUE THREAD

**Issue by williware** [Microsoft/azure-devops-python-api#123]
The get_storage_key function has
         location_id='eb85f8cc-f0f6-4264-a5b1-ffe2e4d4801f'
when calling the function via a graph client (where the code is located) it returns a location error
grph_client.get_storage_key(usrDave.descriptor)
**ValueError: API resource location eb85f8cc-f0f6-4264-a5b1-ffe2e4d4801f is not registered on https://aiz-alm.visualstudio.com.**

-----------------Test w/ each client ------------------------
>>> type(grph_client)
<class 'vsts.graph.v4_1.graph_client.GraphClient'>
>>> type(id_client)
<class 'vsts.identity.v4_1.identity_client.IdentityClient'>

location_id='eb85f8cc-f0f6-4264-a5b1-ffe2e4d4801f'
grph_client._get_resource_location(location_id)
# returns None
>>> id_client._get_resource_location(location_id).__dict__
{'additional_properties': {}, 'id': 'eb85f8cc-f0f6-4264-a5b1-ffe2e4d4801f', 'area': 'Graph', 'resource_name': 'StorageKeys', 'route_template': '_apis/{area}/{resource}/{subjectDescriptor}', 'resource_version': 1, 'min_version': 3.2, 'max_version': 5.0, 'released_version': '0.0'}

**Comment by williware** [comment]
This works for now - copied function from graph.py and now pass in two clients

def get_storage_key(id_client, grph_client, subject_descriptor):
        """GetStorageKey.
        [Preview API] Resolve a descriptor to a storage key.
        :param str subject_descriptor:
        :rtype: :class:`<GraphStorageKeyResult> <graph.v4_1.models.GraphStorageKeyResult>`
        """
        route_values = {}
        if subject_descriptor is not None:
            route_values['subjectDescriptor'] = id_client._serialize.url('subject_descriptor', subject_descriptor, 'str')
        response = id_client._send(http_method='GET',
                              location_id='eb85f8cc-f0f6-4264-a5b1-ffe2e4d4801f',
                              version='4.1-preview.1',
                              route_values=route_values)
        return grph_client._deserialize('GraphStorageKeyResult', response)

**Comment by tedchamb** [comment]
The resource area id is missing on the graph client.  It should be: BB1E7EC9-E901-4B68-999A-DE7012B920F8

**Comment by tedchamb** [comment]
fixed in #133

**Comment by williware** [comment]
Thanks. I'll give it a try

**Comment by tedchamb** [comment]
I have published a new version with the fix: 
https://github.com/Microsoft/azure-devops-python-api/releases/tag/0.1.19
