### ISSUE TITLE
Example for using the "create_attachment" function?

### ISSUE THREAD

**Issue by TheMechanic97** [Microsoft/azure-devops-python-api#129]
I have tried using the path to a file as the upload_stream as well as opening the file to use the contents. 

Using the path returns an ID and URL but they lead to a null (File does not exist) exception. 

Using the contents of the file result in "'utf8' codec can't decode byte 0xff in position 0: invalid start byte".

**Comment by tedchamb** [comment]
Similar issue to #29.  When we fix #29, this should be fixed as well.

**Comment by tedchamb** [comment]
Fix is in #163

**Comment by jfthuong** [comment]
I confirm, upload works fine now!
