### ISSUE TITLE
Wrapper Documentation Quality

### ISSUE THREAD

**Issue by christopherthompson81** [microsoft/azure-devops-python-api#132]
The documentation surrounding this wrapper is poor. The example identifies how to list a set of projects and it works. Great! But what other functions exist? The documentation indicates to use the REST API as a guide as the wrapper is "thin". However, the REST API documentation does not match the wrapper organization.

In python, the "get_projects" call happens by:

1. Establishing a connection
2. Getting a client with a magic client identifier string ('vsts.core.v4_0.core_client.CoreClient') to indicate "core" as the API section
3. Calling "get_projects()" through that client.

In the REST API, the call happens by a GET call to "https://dev.azure.com/{organization}/_apis/projects?api-version=5.0-preview.3"
To find this call, one needs to navigate to: core->projects->list

### Why is this poor documentation?

- The use of magic identifiers is not intuitive or documented. One has to grep code to figure out why such a string would be used.
- "magic string".get_projects() does not intuitively map to either "projects" or core->projects->list. This means that one cannot know how to make a call through the python wrapper by looking at the API documentation.

### What can be done about this?

We can display a list of methods on clients using the signature function from inspect:

```method_list = [method_name for method_name in dir(core_client) if callable(getattr(core_client, method_name))]
	for method_name in method_list:
		if not method_name.startswith('_'):
			method = getattr(core_client, method_name)
			print(method_name + str(signature(method)))
```

This turns up the following:

```
add_user_agent(user_agent)
create_connected_service(connected_service_creation_data, project_id)
create_identity_mru(mru_data, mru_name)
create_or_update_proxy(proxy)
create_team(team, project_id)
delete_proxy(proxy_url, site=None)
delete_team(project_id, team_id)
get_connected_service_details(project_id, name)
get_connected_services(project_id, kind=None)
get_identity_mru(mru_name)
get_process_by_id(process_id)
get_processes()
get_project(project_id, include_capabilities=None, include_history=None)
get_project_collection(collection_id)
get_project_collections(top=None, skip=None)
get_project_history_entries(min_revision=None)
get_project_properties(project_id, keys=None)
get_projects(state_filter=None, top=None, skip=None, continuation_token=None)
get_proxies(proxy_url=None)
get_team(project_id, team_id)
get_team_members(project_id, team_id, top=None, skip=None)
get_teams(project_id, top=None, skip=None)
queue_create_project(project_to_create)
queue_delete_project(project_id)
set_project_properties(project_id, patch_document)
update_identity_mru(mru_data, mru_name)
update_project(project_update, project_id)
update_team(team_data, project_id, team_id)
```

OK, great, now we know the actual names of the functions and their parameters as callable. This is good because they differ from those listed in the API documentation.

### Now what about all the other magic strings? Where do I find them?

I didn't really know where to find them, so I cloned a copy of the source and dug through it.

`grep -R "CoreClient" .`

Turns up the following results

```
./README.md:core_client = connection.get_client('vsts.core.v4_0.core_client.CoreClient')
./vsts/vsts/core/v4_0/core_client.py:class CoreClient(VssClient):
./vsts/vsts/core/v4_0/core_client.py:        super(CoreClient, self).__init__(base_url, creds)
./vsts/vsts/core/v4_1/core_client.py:class CoreClient(VssClient):
./vsts/vsts/core/v4_1/core_client.py:        super(CoreClient, self).__init__(base_url, creds)
```

OK, so now we know that folders in the vsts/vsts folder match up with the REST API, we also can start to see the pattern: vsts/API_section/API_version/snake_case_api_section_file/PascalCaseAPISectionClass

We can also see a correlation to the magic string:  'vsts.core.v4_0.core_client.CoreClient' is just using dots instead of slashes.

BUT! that was far more work than somebody that wants to use this package should have to go through. There should be a document which automatically gets built on commit which provides an MD of the clients and the functions available in each client. There should also be an explanation of the magic strings and why they are the way they are.

Even something as simple as the following would help:
[generate_docs.1.py.zip](https://github.com/Microsoft/azure-devops-python-api/files/2499340/generate_docs.1.py.zip)

**Comment by tedchamb** [comment]
There are also some samples here, which you may find helpful:
https://github.com/Microsoft/azure-devops-python-samples

**Comment by jfthuong** [comment]
@christopherthompson81 

Thanks again for your amazing analysis of this magic string!!

That unblocked me in my quest of parsing Test Results (I'm still struggling to understand what is a query for Test Results but at least I'm going forward).

@tedchamb There are some samples in the repo "azure-devops-python-samples" but they are currently not very rich (only 5 examples) and I created a "request" for that 2 weeks ago.

Cheers

**Comment by tillias** [comment]
Can you please take a look at rcoenmans/vsts-client and add minor documentation as it is done here? E.g. how to create workitem, area, add attachment etc?
Unfortunately autocomplete doesn't work with this library and this is major impedement in using it

**Comment by tedchamb** [comment]
Closing this issue.  The 'magic string' mentioned above has been abstracted away in the 5.0.0 version of the sdk by use of factories to get your client.

Example:
```
# Create a connection to the org
credentials = BasicAuthentication('', personal_access_token)
connection = Connection(base_url=organization_url, creds=credentials)

# Get a client (the "core" client provides access to projects, teams, etc)
core_client = connection.clients.get_core_client()
```

@tillias, please see #186 for more information on your specific example requests.

Suggestions for new examples can be filed in the [azure-devops-python-samples](https://github.com/Microsoft/azure-devops-python-samples) repo.

**Comment by WhatDoesKmean** [comment]
Hey!  Thanks for this useful library. I'm able to retrieve a bunch of fileda regarding work items (User Stories / Tasks / etc.)
I was wondering if you could post a sample demo on how to retrieve Parents and Child items as well in order to be able to correlate them.  
Thanks again for your help!
