### ISSUE TITLE
get_artifact_content_zip returns metadata rather than contents

### ISSUE THREAD

**Issue by slicedlime** [Microsoft/azure-devops-python-api#137]
As described in the subject.

I've managed to get this to work by cloning the entire method, setting `self.config.additional_headers['Accept'] = 'application/zip'`, adding `query_parameters['$format'] = 'zip'` and changing the return statement to `return response.content`. I'd hesitate to call this a solution more than a workaround, but I have no idea what would be a better solution.

**Comment by tedchamb** [comment]
This is a duplicate to #29 and #129.  Dealing with a number of high priorities in other projects, but will try and get something out for this soon.

**Comment by tedchamb** [comment]
https://github.com/Microsoft/azure-devops-python-api/releases/tag/0.1.23
