### ISSUE TITLE
Function `query_test_runs` limited to a time range of 7 days

### ISSUE THREAD

**Issue by jfthuong** [Microsoft/azure-devops-python-api#142]
I am exploring the different ways to retrieve Test Results and I tried the function `query_test_runs`.

Is it normal that the delta between start and end date is limited to 7 days.

In my case, I had the following code:
```python
from datetime import datetime, timedelta
from vsts.vss_connection import VssConnection
...
test_client = connection.get_client("vsts.test.v4_1.test_client.TestClient")

end_date = datetime.today()
start_date = end_date - timedelta(days=8)
plan_ids = [functional_tp]
for run in test_client.query_test_runs(my_project, start_date, end_date):
    for res in test_client.get_test_results(my_project, run.id):
        tc = res.test_case
```

which returned the following Traceback:

```python
Traceback (most recent call last):
  File "c:\SVN\Scripts\Playground\TFS\test_TFS.py", line 93, in <module>
    for run in test_client.query_test_runs(my_project, start_date, end_date):
  File "C:\Python36\lib\site-packages\vsts\test\v4_1\test_client.py", line 1608, in query_test_runs
    returns_collection=True)
  File "C:\Python36\lib\site-packages\vsts\vss_client.py", line 96, in _send
    response = self._send_request(request=request, headers=headers, content=content)
  File "C:\Python36\lib\site-packages\vsts\vss_client.py", line 63, in _send_request
    self._handle_error(request, response)
  File "C:\Python36\lib\site-packages\vsts\vss_client.py", line 243, in _handle_error
    raise VstsServiceError(wrapped_exception)
vsts.exceptions.VstsServiceError: Date Range should be within 7 days
```

**Comment by tedchamb** [comment]
This is a server side error message.  I have contacted the team that owns this api, so we can find out more details about this scenario.

**Comment by puagarwa** [comment]
Hi,
   Sorry for the delay in response, yes this api does have restriction of max of 7 days runs because its a sync api and we wants to keep the query bounded because of the perf impact. I want to understand your scenario to check if there are some other api which you can use in order to get things done. 

BTW, take a look at our rest api documentation related to [runs](https://docs.microsoft.com/en-us/rest/api/vsts/test/runs/query?view=vsts-rest-5.0)

This is list api which can also be used https://docs.microsoft.com/en-us/rest/api/vsts/test/runs/list?view=vsts-rest-5.0

**Comment by jfthuong** [comment]
Hi,

Thanks for the answer.

My use case is the following :
* I need to retrieve all test results at the end of each iteration (3 weeks)
* I have not managed to understand how to use "get_test_results_by_query" (is it still only a preview as indicated in the docstring of the function??)

Will it be possible to extend the maximum duration to 4 weeks by any chance?

Otherwise, would you have an example of how to use queries to retrieve test results?

Thanks a lot
________________________________

**Comment by puagarwa** [comment]
* I need to retrieve all test results at the end of each iteration (3 weeks)
Can i ask for more information around this need, if you are only interested in only let says summary like pass % , etc then i would suggest you to use our reporting apis using build Id or releaseId. 

I am not sure how much data you have but fetching all the results for 3 weeks can be lot of data, so i would like to understand more about the scenario.
BTW, we also have analytics solution which is more suitable for those usecase where we wants to have reports using past data. I will add our analytic experts once you provide more information about use case.
Also, do you have automated test data or manual planned testing data as well ?

* I have not managed to understand how to use "get_test_results_by_query" (is it still only a preview as indicated in the docstring of the function??)
API is public but 5.0 version is still in preview , you can use 4.1 version which is released.

Will it be possible to extend the maximum duration to 4 weeks by any chance?
No, but you can use for loop and get the data for each week using same api.

This is paging api where we provide continuationToken in response header, you can have while loop till token is null. you can have outer loop for date range in a batch of 7 days.

**Comment by jfthuong** [comment]
Thanks for your detailed answer.

What we have:
* More than 1,000 manual test cases (non-regression, new feature, etc.)
* We will probably add several runs for automatic Test Cases

What we want to do:
* Retrieve all test cases and associated results during the current iteration
* My Python script is then generating an Excel report with all the tests
* The script also retrieves all the bugs status

This is an example of report:
![excel report](https://user-images.githubusercontent.com/1401809/48616374-657c9b80-e9ce-11e8-8915-83f3fbc0e375.png)

The script is run at the end of each iteration.

Do you need additional information on my usecase?

Thanks again

**Comment by puagarwa** [comment]
Hi,
  I have asked our PM to take a look at this scenario in detail. We will come back to you soon.

Thanks
Puneet

**Comment by tedchamb** [comment]
@puagarwa you had mentioned following up here after working with your PM.  Do you have anything more to add?

**Comment by puagarwa** [comment]
Apologies for delay, I have asked our PM to look into this issue, we should be closing it soon.

**Comment by divais** [comment]
Hi Jeff,

Automated test results can be retrieved using the Analytics APIs (OData APIs) for longer duration than 7 days. 

However based on your summary above, you are mainly retrieving manual test cases which doesn't have analytics right now so you will have to use the batching mechanism shared by my team before. Manual test analytics is in roadmap and should be available too in a quarter. 

Let me know if you need more assistance on this.

**Comment by jfthuong** [comment]
Thanks a lot.

We are currently upgrading our version of TFS to enable Analytics. I will try this once enabled, or used the week-batch as a workaround meanwhile.

Thank you all for the support
