### ISSUE TITLE
Not able to create relationships between work items

### ISSUE THREAD

**Issue by gnychis** [Microsoft/azure-devops-python-api#153]
I am trying to create relationships between work items using the work item client API.  This relationship seems to be tracked as a high-level /relations property path.  I can't seem to find support for setting these relationships in the API.  If I try to force it via a JsonPatchOperation I get:

> VstsServiceError: Work item patch does not support patching the top level property at path /relations.

How can I create relations via the API?

**Comment by tedchamb** [comment]
@gnychis , you can find an example request body here:

https://docs.microsoft.com/en-us/rest/api/azure/devops/wit/work%20items/update?view=azure-devops-rest-5.0#add_a_link

If that doesn't help, please send us a sample request/response after scrubbing any private data.

You can addd the following code, to print out the request/responses to the console:
```
import logging

logging.basicConfig(level=logging.DEBUG)
```
Thanks,
Ted

**Comment by gnychis** [comment]
Thanks, @tedchamb that was helpful.  I was able to resolve it by using `path="/relations/-"`
