### ISSUE TITLE
How to add Attachment to Test Steps?

### ISSUE THREAD

**Issue by jfthuong** [Microsoft/azure-devops-python-api#155]
I would like to add attachments to some of the steps of my Test Cases like I can do in the Web Interface.

This is how I want my step to look like:

[![Step with attachment][1]][1]

... and when you run it, that would look like this:
[![enter image description here][2]][2]

However, I have not been able to find where this information is stored.

This is the JSON data for the WorkItem of my Test Case

    {
    id: 224,
    rev: 2,
    fields: {
        System.AreaPath: "GM_sandbox\GM-Toto",
        System.TeamProject: "GM_sandbox",
        System.IterationPath: "GM_sandbox",
        System.WorkItemType: "Test Case",
        System.State: "Design",
        System.Reason: "New",
        System.AssignedTo: "Jeff",
        System.CreatedDate: "2019-01-03T01:43:09.743Z",
        System.CreatedBy: "Jeff",
        System.ChangedDate: "2019-01-03T02:12:07.15Z",
        System.ChangedBy: "Jeff",
        System.Title: "Titi",
        Microsoft.VSTS.Common.StateChangeDate: "2019-01-03T01:43:09.743Z",
        Microsoft.VSTS.Common.ActivatedDate: "2019-01-03T01:43:09.743Z",
        Microsoft.VSTS.Common.ActivatedBy: "Jeff",
        Microsoft.VSTS.Common.Priority: 2,
        Microsoft.VSTS.TCM.AutomationStatus: "Not Automated",
        Microsoft.VSTS.TCM.Steps: "<steps id="0" last="2"><step id="2" type="ValidateStep"><parameterizedString isformatted="true">&lt;DIV&gt;&lt;P&gt;Click on the rainbow button&lt;/P&gt;&lt;/DIV&gt;</parameterizedString><parameterizedString isformatted="true">&lt;P&gt;Screen becomes Blue (see picture)&lt;/P&gt;</parameterizedString><description/></step></steps>"
    },
    _links: {
        self: {
            href: "https://my_server.com:8443/tfs/PRODUCT/23d89bd4-8547-4be3-aa73-13a30866f176/_apis/wit/workItems/224"
        },
        workItemUpdates: {
            href: "https://my_server.com:8443/tfs/PRODUCT/_apis/wit/workItems/224/updates"
        },
        workItemRevisions: {
            href: "https://my_server.com:8443/tfs/PRODUCT/_apis/wit/workItems/224/revisions"
        },
        workItemHistory: {
            href: "https://my_server.com:8443/tfs/PRODUCT/_apis/wit/workItems/224/history"
        },
        html: {
            href: "https://my_server.com:8443/tfs/PRODUCTi.aspx?pcguid=4107d6a2-eaaa-40b9-9a8d-f8fdbb31d4b7&id=224"
        },
        workItemType: {
            href: "https://my_server.com:8443/tfs/PRODUCT/23d89bd4-8547-4be3-aa73-13a30866f176/_apis/wit/workItemTypes/Test%20Case"
        },
        fields: {
            href: "https://my_server.com:8443/tfs/PRODUCT/23d89bd4-8547-4be3-aa73-13a30866f176/_apis/wit/fields"
        }
    },
    url: "https://my_server.com:8443/tfs/PRODUCT/23d89bd4-8547-4be3-aa73-13a30866f176/_apis/wit/workItems/224"
    }

Any idea on where this information is stored?

And, if possible, could anyone tell me how to add an attachment from a file and link it to the test step?

Thanks a lot

  [1]: https://i.stack.imgur.com/bPBQn.png
  [2]: https://i.stack.imgur.com/c6Xkd.png

**Comment by tedchamb** [comment]
Seleha from the TCM team has provided us with this helpful information:

> This will be a two step process
> 1.	The first step is to add an attachment to the test case work item. 
> This can be done using this API - https://docs.microsoft.com/en-us/rest/api/azure/devops/wit/attachments/create?view=azure-devops-rest-5.0
> 2.	To attach the uploaded attachment to the test step, you can use this API sample - https://docs.microsoft.com/en-us/rest/api/azure/devops/wit/work%20items/update?view=azure-devops-rest-5.0#add_an_attachment with comment as [TestStep=<id>] and URL as obtained from the previous API.
> If however you are open to using C# or JS clients, this step is simplified. The samples can be found here - https://blogs.msdn.microsoft.com/devops/2016/11/02/how-to-use-test-step-using-rest-client-helper/
> 
> Regards
> Saleha

In the python code the methods for step 1 and 2 can be found here:
1. WorkItemTrackingClient [create_attachment](https://github.com/Microsoft/azure-devops-python-api/blob/1bacd2a3f0128a6d184cf75e2c6f8859d46f270a/vsts/vsts/work_item_tracking/v4_1/work_item_tracking_client.py#L56)
2. WorkItemTrackingClient [update_work_item](https://github.com/Microsoft/azure-devops-python-api/blob/1bacd2a3f0128a6d184cf75e2c6f8859d46f270a/vsts/vsts/work_item_tracking/v4_1/work_item_tracking_client.py#L1353)

I hope this helps,
Ted

**Comment by jfthuong** [comment]
Thank you for the answer, that will help a bit to understand.

Could you tell me actually what is the `stream` for the `create_attachment` function?
```python
    def create_attachment(self, upload_stream, project=None, file_name=None, upload_type=None, area_path=None):
        """CreateAttachment.
        Uploads an attachment.
        :param object upload_stream: Stream to upload
        ...
        """
```

I tried both solutions below but none seems to work:

```python
with open('./smiley.png', "rb") as f:
    binary_content = bytes(f.read())
attachment = client_wit.create_attachment(binary_content, project, 'smiley.png')
```

```python
attachment = client_wit.create_attachment("Hello my friend", project, 'test6.txt')
```

Thanks

**Comment by tedchamb** [comment]
@jfthuong , sorry about that.  There is currently a bug blocking uploads, that is being tracked is being tracked by #129.  Hope to get this resolved soon.

**Comment by jfthuong** [comment]
I see.

Hope it will be resolved soon.

The only step I miss is that one (uploading a file correctly).

This the code I have used for attaching an uploaded attachment to a Test Step:

```python
def add_attachment(wit_id: int, project: str, url:str, comment: str, name:str = None):
    """Add attachment already uploaded to a WorkItem"""
    # We want to have the possibility to set a comment
    attributes = {"comment": comment}
    if name is not None:
        attributes["name"] = name

    patch_document = [
        JsonPatchOperation(
            op="add",
            path="/relations/-",
            value={
                "rel": "AttachedFile",
                "url": url,
                "attributes": attributes,
            },
        )
    ]
    return wit_client.update_work_item(patch_document, wit_id, project)

def add_attachment_to_step(tc_id:int, project:str, url:str, step:int, comment="", name=""):
    """Add an attachment to a given step of a Test Case"""
    name = name if name else re.sub(r".*fileName=", "", url)
    comment = f"[TestStep={step}]:{comment}"
    return add_attachment(tc_id, project, url, comment, name)

attachment = client.wit.create_attachment(my_stream, project, 'my_picture.png')
add_attachment_to_step(my_tc, project, attachment.url, 3, "Expected result")
```

I will close the issue and hope #129  to be solved very soon.

Thanks again for the support

**Comment by jfthuong** [comment]
Awesome!!!

**Comment by bbalfour5** [comment]
The example method seems to be working for me, except I get the error JsonPatchOperation is not defined. Is there a library or extension I need to use for it?
