### ISSUE TITLE
get_pull_request_iteration_changes only return change_tracking_id

### ISSUE THREAD

**Issue by roofkitty** [microsoft/azure-devops-python-api#166]
I try to use get_pull_request_iteration_changes  to get files that are change in this iteration as shown [here](https://docs.microsoft.com/en-us/rest/api/azure/devops/git/pull%20request%20iteration%20changes/get?view=azure-devops-rest-5.0).

I copy and paste the desired output from the documentation below.
{
  "changeEntries": [
    {
      "changeTrackingId": 1,
      "changeId": 1,
      "item": {
        "objectId": "e21e56d119ae81fb4ffebc4fefc6351f5b5ef888",
        "path": "/new_feature.cpp"
      },
      "changeType": "add"
    },
    {
      "changeTrackingId": 2,
      "changeId": 2,
      "item": {
        "objectId": "5ec0f71ffb8b47bd4c0117f624647963e021f3d2",
        "path": "/new_feature.h"
      },
      "changeType": "add"
    }
  ]
}

However, when I use get_pull_request_iteration_changes, I can only see changeTrackingId. I wonder if what is the proper way to get above schema, particular the path of the item.

`
client.get_pull_request_iteration_changes(repo_id, pull_request_id, 2, compare_to=1).as_dict()`
{'change_entries': [{'change_tracking_id': 1}, {'change_tracking_id': 4}]}

**Comment by tedchamb** [comment]
Try this:

```
git_client = connection.clients_v5_0.get_git_client()
changes = git_client.get_pull_request_iteration_changes(repo_id, pr_id, 2, compare_to=1)
for change in changes.change_entries:
    pprint.pprint(change.additional_properties['item']['path'])
```

**Comment by tedchamb** [comment]
I am going to close this issue.  Please let me know if the above code sample was not helpful.
