### ISSUE TITLE
While adding test result to a test run, a related bug does not seem to be added

### ISSUE THREAD

**Issue by jfthuong** [Microsoft/azure-devops-python-api#172]
Hi,

I am trying to add test results to Test Run.

I have been pretty successful so far for `duration`, `run_by`, dates, etc... but I cannot make it work for `associated_bugs`.

What puzzles me also is the lack of consistency between the Python API (`TestResultCreateModel` class) and the [official documentation](https://docs.microsoft.com/en-us/rest/api/azure/devops/test/results/add?view=azure-devops-rest-5.0&viewFallbackFrom=azure-devops-rest-4.1) [strangely, I cannot find the page about adding Test Results for version 4.1, that I am using, but only for 5.1).

The `TestResultCreateModel` class has the following prototype:
```python
class TestResultCreateModel(Model):
    """TestResultCreateModel.

    :param area:
    :type area: :class:`ShallowReference <test.v4_1.models.ShallowReference>`
    :param associated_work_items:
    :type associated_work_items: list of int
    ...
```

While documentation and the objects created (with API or Web Interface), have the attribute `'associated_bugs'`.

I have the following code, and the test result is added, but without the link to bug:
```python
new_results = list()
...
result_attrib = {
	"associated_work_items": [245],
	"comment": "Dummy test, failed and linked to issue #245",
	"configuration": {"id": configuration_id},  # Windows 10
	"duration_in_ms": "10000",  # in ms
	"failure_type": "Regression",
	"outcome": "Failed",
	"state": "Completed",
	"test_case": {"id": tc_id},
	"test_point": {"id": point.id},
}  # type: ignore
new_results.append(TestResultCreateModel(**result_attrib))
test_client.add_test_results_to_test_run(new_results, project, run_id)
```

Is it an issue or is there a way to link a Test Result to a bug?

Thanks

**Comment by tedchamb** [comment]
@jfthuong , the [`add_test_results_to_test_run`](https://github.com/Microsoft/azure-devops-python-api/blob/709488b910ca43d802392974613ff014381534a2/vsts/vsts/test/v4_1/test_client.py#L1147) method takes a list of instances of [`TestCaseResult`](https://github.com/Microsoft/azure-devops-python-api/blob/0d9537016bd45cf7f2140433c0ec54b44768f726/vsts/vsts/test/v4_1/models/test_case_result.py#L12) rather than `TestResultCreateModel`.

**Comment by jfthuong** [comment]
Indeed, it's strange that I missed that and even stranger that it worked ;)

How to create a `TestCaseResult` then? Shall we use `TestResultCreateModel`?

**Comment by jfthuong** [comment]
What is the purpose of TestResultCreateModel then?

**Comment by tedchamb** [comment]
The best I can tell is that the older versions of this controller take TestResultCreateModel, and it looks like they have switched back to it on the 5.1 controller, but the 4.x controllers take in the TestCaseResult.
