### ISSUE TITLE
ModuleNotFound NuGetClient

### ISSUE THREAD

**Issue by thisisnaty** [Microsoft/azure-devops-python-api#181]
I'm trying to use the FeedClient and NuGetClient to download a package from a feed. Getting the feed client works fine:
```
feed_client = connection.get_client('azure.devops.v5_0.feed.feed_client.FeedClient')
```

But when I try to do the same for the nuget client I get an error saying

> Exception has occurred: ModuleNotFoundError
> No module named 'azure.devops.v5_0.nuget.nuget_client.NuGetClient'

**Comment by thisisnaty** [comment]
I made it work by renaming the files a little bit. Instead of `nuGet/nuGet_client` I did `nuget/nuget_client`. Should you guys update it or is this related to my Python version? I'm using 3.6.8

**Comment by tedchamb** [comment]
Its a bug, the folder and file name should be lowercase.  I will fix this.

On a side note, you should leverage the new client factories.  Its not a work around for this bug, but it does making getting the clients easier.

`feed_client = connection.clients_v5_0.get_feed_client()`

**Comment by tedchamb** [comment]
#182

**Comment by tedchamb** [comment]
The fix has been published:
https://github.com/Microsoft/azure-devops-python-api/releases/tag/5.0.0b2

**Comment by tedchamb** [comment]
@thisisnaty Thanks for reporting this.  I am going to close this out.  Please let me know if you have any other issues.

**Comment by thisisnaty** [comment]
Thank you so much!
