### ISSUE TITLE
Cannot update ref using git_client.update_ref()

### ISSUE THREAD

**Issue by furiousxk** [Microsoft/azure-devops-python-api#192]
Hello,

Using the python API I cannot seem to lock a branch as defined here https://docs.microsoft.com/en-us/rest/api/azure/devops/git/refs/update%20ref?view=azure-devops-rest-5.0.

I have the following implementation

        refs = git_client.get_refs(repository.id)
        for ref in refs:
            if ref.name.split('/')[2] == branch_name:
                if ref.is_locked is False:
                    try:
                        git_client.update_ref(new_ref_info={"is_locked": True}, repository_id=repository.id, filter=branch_name)
                    except Exception as e:
                        print e.message, e.args

I have also tried specifying the Project as well as the repository.name instead of the repository.id but it did not help/change anything.

Despite knowing/confirming the branch **exists** i'm thrown an error: 

> TF401020: The Git ref with name refs/**branchname** does not exist in the repository with name or identifier **repository.id**.

I have tried to google this error or the shortcode TF401020 but to no avail.

If there's any additional information needed I'll gladly supply that.

Kind regards.

**Comment by tedchamb** [comment]
Here is some sample code:

```
patch = GitRefUpdate(is_locked=True)
ref = git_client.update_ref(patch, 'MyFirstProject', 'heads/master', project=project)
print(ref.is_locked)
```

**Comment by tedchamb** [comment]
@furiousxk was this sample code helpful, or are you still having issues?

**Comment by furiousxk** [comment]
@tedchamb Hi Ted, apologies for late response.
I've imported `GitRefUpdate` from `azure.devops.v5_1.git.models` and tried your suggested solution.
Unfortunately I am still presented with the same error.
Below is a small snippet of my code

```
repositories = git_client.get_repositories()

for repository in repositories:
    if repository.name not in to_exclude:
        refs = git_client.get_refs(repository.id)
        for ref in refs:
            if ref.name.split('/')[2].lower() == branch_name.lower():
                if ref.is_locked is True:
                    print('Branch is locked by' + ref.is_locked_by.unique_name)
                else:
                    try:
                        patch = GitRefUpdate(is_locked: True)
                        git_client.update_ref(patch, repository_id=repository.id, filter=branch_name.lower())
                    except Exception as e:
                        print e.message, e.args
```

`branch_name` is a variable which is filled upon user input ( a user can define a specific branch to lock )

Despite changing the implementation to using the `GitRefUpdate` model I am still thrown

`TF401020: The Git ref with name refs/*branch_name* does not exist in the repository with name or identifier *repository.id*. (u'TF401020: The Git ref with name refs/*branch_name* does not exist in the repository with name or identifier *repository.id*.',)`

I have stripped out the specific branch name and repository id.

Thanks in advance, kind regards.

**Comment by furiousxk** [comment]
I found the issue,

If i change the filter from

`filter=branch_name` to `filter= 'heads/' + branch_name`

It works.

Thanks for all help.
