### ISSUE TITLE
Documentation for TestRun differing from TestRun model

### ISSUE THREAD

**Issue by cdietschrun** [Microsoft/azure-devops-python-api#193]
Docs for the TestRun response object from a create or get of a TestRun here shows the last item is a "webResultUrl":

https://docs.microsoft.com/en-us/rest/api/azure/devops/clt/test%20runs/create?view=azure-devops-rest-5.0#testrun

Source code of the API which we're using here shows it's access in Python via "web_access_url" or maybe "webAccessUrl":

https://github.com/Microsoft/azure-devops-python-api/blob/dev/azure-devops/azure/devops/v5_0/test/models.py#L3643

Can we update the docs to reflect webAccessUrl? The .NET docs look like they reference webAccessUrl:

https://docs.microsoft.com/en-us/dotnet/api/microsoft.teamfoundation.testmanagement.webapi.testrun?view=azure-devops-dotnet

**Comment by tedchamb** [comment]
You are looking at three different things:

Over the wire the property is camel case:  webAccessUrl.  This is always the serialized form.   
In python properties are all lowercase with underscore: web_access_url.   
In c# the properties are capitalized: WebAccessUrl.

**Comment by cdietschrun** [comment]
Sure, but why is the REST API doc reference it as web*Request*Url ?

**Comment by tedchamb** [comment]
So the first link you provided is for the Cloud Load Test client, which has a different contract named TestRun.   The second two links are referring to the Test Management client.

The Test Management REST documentation is here:
https://docs.microsoft.com/en-us/rest/api/azure/devops/test/runs/create

The return type is TestRun, which has a webAccessUrl property.

**Comment by cdietschrun** [comment]
Ah I see. Closing. Thanks.
