### ISSUE TITLE
Cannot access Release Client

### ISSUE THREAD

**Issue by HackyPenguin** [Microsoft/azure-devops-python-api#196]
I cannot seem to access the release client.

from azure.devops.v5_0.release import ReleaseClient

```    def get_release(self):
        self.rc = ReleaseClient(base_url=self.url, creds=self.creds)
        a = self.rc.get_release_definitions(project=self.projectname, search_text=self.service )
```
I simply get ValueError: API resource location d8f96f24-8ea7-4cb6-baab-2df8fc515665 is not registered on https://company.visualstudio.com.

the same baseurl works for the Build Client.

**Comment by tedchamb** [comment]
This is because `Release` is a different service and has a different url.  You should be using the client factories to get the clients, which will look up the correct url for you.  You can then use the same connection to get the Build client and the Release client.

```
organization_url = https://dev.azure.com/<organization>
credentials = BasicAuthentication('x', personal_access_token)
connection = Connection(base_url=organization_url, creds=credentials)
release_client = connection.clients.get_release_client()
build_client = connection.clients.get_build_client()
```

**Comment by tedchamb** [comment]
@HackyPenguin I am going to close this issue.  Please let me know if it did not fix your problem.

Thanks,
Ted
