### ISSUE TITLE
TFS 2018 Update 1

### ISSUE THREAD

**Issue by ScFix** [Microsoft/azure-devops-python-api#201]
Does this python API support TFS 2018 Update 1? Or only AzureDevops ?

**Comment by tedchamb** [comment]
For best results use the older vsts version of the tool for TFS 2018 Update 1, and use the 4.0 apis.

Last Release as of this post:
https://github.com/Microsoft/azure-devops-python-api/releases/tag/0.1.25

Branch:
https://github.com/Microsoft/azure-devops-python-api/tree/releases/vsts
