### ISSUE TITLE
[question] Is it safe to use the Identity APIs even though it is not documented?

### ISSUE THREAD

**Issue by arvinatwork** [microsoft/azure-devops-python-api#203]
We need to call some api's that need identities. Is there alternative api for getting identities? 
 
For example we need to do these:
- Add team administrator for a project group: missing api or location id  _apis/_identities/AddTeamAdmins
- Add release approvers in release pipeline environments: ReleaseDefinitionApprovalStep needs identity

**Comment by tedchamb** [comment]
The Graph apis are meant to replace the Identity apis, but the Identity apis will continue to work, and are safe to use.

**Comment by arvinatwork** [comment]
Alright thank you! Do you have any suggestion on what to use for endpoints that requires IdentityRef without using the identity api?

**Comment by kigunda** [comment]
So for those APIs, the identity ref object will be filled in with either "descriptor" or "id". For the authenticated user you can retrieve these using the /_apis/connectionData endpoint. For other users you can retrieve these using the [get users](https://docs.microsoft.com/en-us/rest/api/azure/devops/graph/Users/Get?view=azure-devops-rest-5.0) and [get storage keys](https://docs.microsoft.com/en-us/rest/api/azure/devops/graph/storage%20keys/get?view=azure-devops-rest-5.0) endpoints respectively
