### ISSUE TITLE
Can't access workItem.fields['Microsoft.VSTS.Scheduling.StartDate'] or other Scheduling fields

### ISSUE THREAD

**Issue by corbyjames** [microsoft/azure-devops-python-api#204]
Could be something I'm doing, but I'm pulling other fields back fine.  When I try to access workItem.fields['Microsoft.VSTS.Scheduling.StartDate' or workItem.fields['Microsoft.VSTS.Scheduling.TargetDate
I get a KeyError.

Can someone try it and see if it works for them?  I verified that it is in the response...
   'Microsoft.VSTS.Scheduling.TargetDate': '2019-12-01T06:00:00Z',

**Comment by tedchamb** [comment]
The following works fine for me.  Keep in mind that not all work items will have these entries.
```
wit_client = connection.clients.get_work_item_tracking_client()
work_item = wit_client.get_work_item(id=992)
if 'Microsoft.VSTS.Scheduling.StartDate' in work_item.fields:
    start_date = work_item.fields['Microsoft.VSTS.Scheduling.StartDate']
if 'Microsoft.VSTS.Scheduling.TargetDate' in work_item.fields:
    target_date = work_item.fields['Microsoft.VSTS.Scheduling.TargetDate']
```
