### ISSUE TITLE
Python client does not allow sending if-match headers in the request e.g in wiki page update 

### ISSUE THREAD

**Issue by atbagga** [microsoft/azure-devops-python-api#205]
In [WikiClient ](https://github.com/Microsoft/azure-devops-python-api/blob/006129675c454c7a8e25b4f729c49d9866fbd587/azure-devops/azure/devops/released/wiki/wiki_client.py)
create_or_update_page function accepts version of the old page which needs to be passed to the API in the if-match header. This is not possible in the python client right now. 

For now fixing the issue in devops extension like this-
https://github.com/Azure/azure-devops-cli-extension/pull/533

**Comment by tedchamb** [comment]
Fixed in #219

**Comment by tedchamb** [comment]
Fixed in release [5.0.0b7](https://github.com/microsoft/azure-devops-python-api/releases/tag/5.0.0b7)
