### ISSUE TITLE
Is there a way to set the request timeout?

### ISSUE THREAD

**Issue by corbyjames** [microsoft/azure-devops-python-api#208]
I keep getting RetryErrors on some calls (Capacity).  I think it because the timeout value (100) is too short.  Is there a way to override that value?

**Comment by tedchamb** [comment]
Try changing the timeout on your client like this:

```
location_client = connection.clients_v5_0.get_location_client()
location_client.config.connection.timeout = 150
```

**Comment by tedchamb** [comment]
I am going to close this out.  Let me know if you still have issues.
