### ISSUE TITLE
How can i get Test Case passed or failed?

### ISSUE THREAD

**Issue by zhangAiden** [microsoft/azure-devops-python-api#209]
I use _workitem_Client.getworkitem(testCaseId)_,how can i get the state of TestCase :passed or failed? i found when i  use it to get the workitemResults ,but the response didn't contained the test result passed or failed?

**Comment by zhangAiden** [comment]
if the test case is manual test ,i find the automation test case result can get

**Comment by tedchamb** [comment]
This is from the test team:

"The programmatic way to get the test result is through this [REST API](https://docs.microsoft.com/en-us/rest/api/azure/devops/test/results/get?view=azure-devops-rest-5.0). Test Case is a reusable entity and hence we don’t add the test result to it. It is through test result that the status (passed/failed/…) is stored and surfaced. "

The REST API doc they refer to corresponds to ```get_test_result_by_id``` in the [```TestClient```](https://github.com/microsoft/azure-devops-python-api/blob/dev/azure-devops/azure/devops/v5_0/test/test_client.py) class.

**Comment by zhangAiden** [comment]
Thanks , I want to how to use the TestClient.get_test_results_by_query ,how can i write the query content?

**Comment by tedchamb** [comment]
@zhangAiden , are you targeting an on-prem TFS 2018 server or are you targeting the hosted service.  If you are targeting the service, I would recommend you switch to the latest version of the `azure-devops` package.  Note that the package name has changed from `vsts` to `azure-devops`.  In the latest version the `get_test_results_by_query` method no longer exists, but you will find the matching documentation and REST examples for the `Test` APIs at the following link.  This is documentation for the REST API, but this python package is just a thin wrapper around those APIs.  The examples provided in the docs should help you when using the corresponding python methods.

https://docs.microsoft.com/en-us/rest/api/azure/devops/test/?view=azure-devops-rest-5.0

**Comment by ARedGear** [comment]
How do I use the Get function in Python? 
I'm wanting to add a line in my python script that goes and gets the data from using this "GET https://dev.azure.com/{organization}/{project}/_apis/test/Runs/{runId}/results/{testCaseResultId}?api-version=5.0" 

How do I "Wrap" this in python to make it work in my scrip?

(I should note I've already taken care of setting up my token and such)
