### ISSUE TITLE
Cannot create a new user as GraphUserPrincipalNameCreationContext is not available

### ISSUE THREAD

**Issue by AnjanaAK** [microsoft/azure-devops-python-api#225]
How can I create a user in azure devops from AAD given the python client API ? 

How to create GraphUserCreationContext that should be passed as a parameter to create_user function? This is where you can find the function to create a user:
https://github.com/microsoft/azure-devops-python-api/blob/dev/azure-devops/azure/devops/v5_0/graph/graph_client.py

But on the client, where it asks for a graphusercreationcontext, it only asks for a storagekey. And the warning here states that we shouldn't use this for creation of a user:
https://docs.microsoft.com/en-us/rest/api/azure/devops/graph/users/create?view=azure-devops-rest-5.0

The dontet samples uses GraphUserPricipalNameCreationContext : https://github.com/microsoft/azure-devops-dotnet-samples/blob/master/ClientLibrary/Samples/Graph/UsersSample.cs .

But I can't find that as a model class in python.

Just want to verify if this API, particularly the Graph module, is ready to be consumed and used or this particular one is still at preview?

**Comment by tedchamb** [comment]
This is a duplicate to this issue:  #176 

The generator does not know about the sub types, so does not generate them.  We need to fix that.  In the meantime you should be able to create your own sub types for these.

**Comment by AnjanaAK** [comment]
> This is a duplicate to this issue: #176
> 
> The generator does not know about the sub types, so does not generate them. We need to fix that. In the meantime you should be able to create your own sub types for these.

Do you mean that I should define a GraphUserPrincipalNameCreationContext class in my code itself and then use it?
