### ISSUE TITLE
Sample code for create work item

### ISSUE THREAD

**Issue by corbyjames** [microsoft/azure-devops-python-api#226]
Hi can someone post a code snippet for work item creation?  When I do the following, I get an error on the JsonPatchObject.

op = WorkItemFieldOperation(name='add')
jsonPatch = JsonPatchOperation(from_=None,op=op,path="/fields/System.Title",value="Test")
tWorkItem = work_tracker_client.create_work_item(document=jsonPatch,project="BlueKC_Test",type='Epic',validate_only=None, bypass_rules=None, suppress_notifications=None,expand=None)

get this error: 

TypeError: 'JsonPatchOperation' object is not iterable

Thanks!

**Comment by corbyjames** [comment]
Looking at some C# code examples, it looks like JsonPatchDocument is missing from the work_item_tracking models.  Have you tested the create work item method?

**Comment by tedchamb** [comment]
Here is some example code from the azure-devops-cli-extension:

https://github.com/Azure/azure-devops-cli-extension/blob/768aff8971aad2e194fa26d796d47b3a67292b4e/azure-devops/azext_devops/dev/boards/work_item.py#L24

**Comment by corbyjames** [comment]
Thanks Ted!  It makes sense that the document is just a list of operations.
