### ISSUE TITLE
Incorrect location_id in the v5_0 get_comment

### ISSUE THREAD

**Issue by jamiemaclennan** [microsoft/azure-devops-python-api#230]
The wrapper for get_comment in azure\devops\v5_0\work_item_tracking\work_item_tracking_client.py uses the location_id for *get_comments* and therefore doesn't work.

https://github.com/microsoft/azure-devops-python-api/blame/dev/azure-devops/azure/devops/v5_0/work_item_tracking/work_item_tracking_client.py#L313

**Comment by tedchamb** [comment]
What issue are you running into?  Both get_comment and get_comments use the same route, hence have the same location id.   When an ID is supplied a different controller method is invoked.  Make sure you are passing an a work item id to the method.

**Comment by tedchamb** [comment]
@jamiemaclennan , I am going to close this issue.  Please let me know if you are still havign problems with these methods.
