### ISSUE TITLE
Passed Tests always 0 

### ISSUE THREAD

**Issue by abist** [microsoft/azure-devops-python-api#232]
The `test_client` in v5.0 has 2 methods -
1. `get_test_runs` 
2. `query_test_runs`

`get_test_runs` returns the correct number of passed tests for the Test Run but `query_test_runs` always gives passed tests as 0, for the same Test Runs.

**Comment by tedchamb** [comment]
@abist, can you send sample request/response for both requests, so I can see if this is an issue with the endpoint or the sdk.  You can get the request/response by doing one of the following.  Be sure to redact any private data before sending the information.

Enable logging:
```
import logging

logging.basicConfig(level=logging.DEBUG)
```

Use [fiddler](https://www.telerik.com/download/fiddler):
```
connection = Connection(base_url=organization_url, creds=credentials)
connection.use_fiddler = True
```

**Comment by tedchamb** [comment]
@abist, I am going to close this issue for now.  If you are able to send us the additional information I will reopen it.
