### ISSUE TITLE
Unable to create_test_result_attachment for that particular testcases run id 

### ISSUE THREAD

**Issue by WIINAI-KKUMAR** [microsoft/azure-devops-python-api#233]
Hi Team, 

We are not able to attach file to specific  testcases run id. I tried to check entire  packages,  founded **_create_test_result_attachment_** method is available but when i used that method observed  that : "AttributeError: 'TestClient' object has no attribute 'create_test_result_attachment'" . 

Note : Apart from above issues, There Version issues(V5_0 / V5_1), Please make sure one release accessible.

![creat attachments](https://user-images.githubusercontent.com/37238369/59966917-70894280-9540-11e9-854b-fdd577cbe610.PNG)

Thank you so much.!
Vinaykumar .

**Comment by WIINAI-KKUMAR** [comment]
If I import method directly by specifying version of azure. i am able to upload attachment.
Please refer below screenshot for successful upload . 

![image](https://user-images.githubusercontent.com/37238369/59968683-3d07e180-955b-11e9-8a55-77508d2b703a.png)

**Comment by tedchamb** [comment]
It is recommended to use the client factories to get the clients, although that is not what caused the method not to be found.  There are three versions of the clients available for you to use off the Connection factory object:

`test_client = connection.clients.get_test_client()` - This [client](https://github.com/microsoft/azure-devops-python-api/blob/dev/azure-devops/azure/devops/released/test/test_client.py) only includes 5.0 released methods.  When we release the 5.1 apis, this client will automatically re-target 5.1 released methods in the next version.  When we do that the package version will change to 5.1.x.
`test_client = connection.clients_v5_0.get_test_client()` - This [client](https://github.com/microsoft/azure-devops-python-api/blob/dev/azure-devops/azure/devops/v5_0/test/test_client.py) includes all 5.0 methods (preview and released)
`test_client = connection.clients_v5_1.get_test_client()` - This [client](https://github.com/microsoft/azure-devops-python-api/blob/dev/azure-devops/azure/devops/v5_1/test/test_client.py) includes all 5.1 methods (they are all currently in preview)

Apparently the `create_test_result_attachment` method is still in preview in 5.0, so you will need to request either the 5.0 or 5.1 client to access it.
