### ISSUE TITLE
Examples how to create resources 

### ISSUE THREAD

**Issue by jashan05** [microsoft/azure-devops-python-api#234]
Hello Team,

Could you please provide an example to how to do POST requests using this API. e.g I want to create a Project in Azure DevOps using this API.. How can i do that.

Thanks
JS

**Comment by tedchamb** [comment]
The [azure-devops-cli-extension](https://github.com/Azure/azure-devops-cli-extension) uses our SDK, and provides lots of good examples.  Here is one for create project, which queues the project creation, and checks and waits for the creation job to complete.

https://github.com/Azure/azure-devops-cli-extension/blob/3d591e0c6a7548c1d0e65d9e985313cfe05964a3/azure-devops/azext_devops/dev/team/project.py#L20

@vtbassmatt , this would be a good sample to add to the [azure-devops-python-samples](https://github.com/microsoft/azure-devops-python-samples) repo.  It involves queuing a project, and then using the operation_client to query the creation job progress.
