### ISSUE TITLE
Cleaner way to initialize endpoint object in authorization

### ISSUE THREAD

**Issue by rifaterdemsahin** [microsoft/azure-devops-python-api#241]
> 	import azure.devops.v5_1.service_endpoint.models as endpointmodels
> 	endpoint = endpointmodels.ServiceEndpoint(type = "AWS")
> 	endpoint.name = connectionname
> 	endpoint.authorization = {'parameters': {'username': accesskeyid, 'password': secretaccesskey}, 'scheme': 'UsernamePassword'}
> 	core_client.create_service_endpoint(project = project, endpoint = endpoint)

I would like to find a way to initialize AWS endpoint authorization in a type-safe manner.

**Comment by tedchamb** [comment]
endpoint.authorization is of type `endpointmodels.EndpointAuthorization`, so you can do something like this:

```
endpoint.authorization = endpointmodels.EndpointAuthorization()
endpoint.authorization.parameters = {'username': accesskeyid, 'password': secretaccesskey}
endpoint.authorization.scheme = 'UsernamePassword'
```

Is this what you are asking?

**Comment by tedchamb** [comment]
@rifaterdemsahin, I am going to close this issue.  Please let me know if the answer did not properly address your question.
