### ISSUE TITLE
Support for Azure Common Client Factory

### ISSUE THREAD

**Issue by ncbrown1** [microsoft/azure-devops-python-api#251]
In other `msrest` SDKs, we are able to leverage `from azure.common.client_factory import get_client_from_cli_profile`, which lets us avoid having to handle authentication configuration in code and instead rely on the credentials set up during `az login`. Is it possible to use this for the azure devops clients?

Docs: https://docs.microsoft.com/en-us/python/api/azure-common/azure.common.client_factory?view=azure-python#get-client-from-cli-profile-client-class----kwargs-

**Comment by tedchamb** [comment]
See how they are doing this in the azure-devops-cli-extension:

https://github.com/Azure/azure-devops-cli-extension/blob/94a8d0c21d47f771c0ec177ba9e079c2669dc658/azure-devops/azext_devops/dev/common/services.py#L54

**Comment by tedchamb** [comment]
@ncbrown1 , I am going to close this for now.  Please let me know if you are still having issues.
