### ISSUE TITLE
Permission error when accessing Graph/Avatar with a Full Access PAT

### ISSUE THREAD

**Issue by KaiWalter** [microsoft/azure-devops-python-api#253]
I'm using 5.1.0b1 to access Azure DevOps Graph.

The PAT I'm using is marked 'Full access' and works successfully to e.g. read/write Entitlements and Memberships.

When accessing Avatar for a user, this error is raised:

DEBUG:urllib3.connectionpool:https://vssps.dev.azure.com:443 'GET /myaccount/_apis/Graph/Subjects/aad.OTExMjU4N2ItNzc5Zi03YmI3LWFiYTctOTEwNGJmYTBkNzQw/Avatars HTTP/1.1' 403 762
DEBUG:azure.devops.client:Response content: b'{'$id':'1','customProperties':{'Descriptor':'Microsoft.IdentityModel.Claims.ClaimsIdentity;82913d90-8716-4025-a8e8-4f8dfa42b719\\\\\\\\citsvstsadmin@czcit.onmicrosoft.com','IdentityDisplayName':'VSTS Administrator','Token':'/aad.OTExMjU4N2ItNzc5Zi03YmI3LWFiYTctOTEwNGJmYTBkNzQw','RequestedPermissions':1,'NamespaceId':'140709a6-4d6e-4e13-bea4-8ecbf3d20435'},'innerException':null,'message':'Access Denied: VSTS Administrator needs the following permission(s) on the resource /aad.OTExMjU4N2ItNzc5Zi03YmI3LWFiYTctOTEwNGJmYTBkNzQw to perform this action: Read user properties and attributes.','typeName':'Microsoft.VisualStudio.Services.Security.AccessCheckException, Microsoft.VisualStudio.Services.WebApi','typeKey':'AccessCheckException','errorCode':0,'eventId':3000}'
DEBUG:msrest.exceptions:Access Denied: ***VSTS Administrator needs the following permission(s) on the resource /aad.OTExMjU4N2ItNzc5Zi03YmI3LWFiYTctOTEwNGJmYTBkNzQw to perform this action: Read user properties and attributes.***

**Comment by KaiWalter** [comment]
this is an API issue - when I directly access the API with Postman / PowerShell 80% of the requests fail and 20% succeed.

**Comment by KaiWalter** [comment]
I opened a support case for this: 119080322000005

**Comment by andyfisher100** [comment]
@KaiWalter Did MS support solve this issue for you? We have just hit the same problem in my organisation

**Comment by KaiWalter** [comment]
@andyfisher100 yes, it had been resolved but I needed to bump up to v6 API : https://github.com/KaiWalter/azure-devops-principalName-migration/blob/b5cdae45f47bcdcfb9c70e3c4e0d7fd2d59eb89e/modules/rebuild.py#L189
