### ISSUE TITLE
API doesn't support creating pipelines of YAML

### ISSUE THREAD

**Issue by JerryValentine** [microsoft/azure-devops-python-api#255]
Hi,

I am currently trying to automate the creation of the repositories and build pipelines using this wrapper around the api. I am trying to attach a policy to both the master and develop branches that will trigger the pipeline on pull requests. In order to add that policy I must have the id number of the pipeline. This is where my problem comes into I was going to use the v5.1 pipeline client to create the pipeline and then use the id it provides, but I gives me this error: azure.devops.exceptions.AzureDevOpsServiceError: This API does not support creating pipelines of configuration type Yaml.

Is this going to be added soon or do you know of any way around this?

**Comment by atbagga** [comment]
azure-devops extension (on Azure CLI) uses 5.0 client to create yaml pipelines.  Here is a [blog ](https://devblogs.microsoft.com/devops/create-and-manage-azure-pipelines-from-the-command-line/) on the same. 
The azure-devops extension should help you achieve you use case. If you still want to use REST APIs you can get the POST call by running the command with --debug flag.
