### ISSUE TITLE
Create Work Item failed because of type can not be replaced in url

### ISSUE THREAD

**Issue by conhua** [microsoft/azure-devops-python-api#259]
/_apis/wit/workItems/${type}

When I call create work item, type is not replaced by the parameter
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-17-2a0798f6c8bc> in <module>
----> 1 work_item_client.create_work_item(document=document, project='Cognitive Services', type='Task')

~\AppData\Local\Continuum\anaconda3\lib\site-packages\azure\devops\released\work_item_tracking\work_item_tracking_client.py in create_work_item(self, document, project, type, validate_only, bypass_rules, suppress_notifications, expand)
   1082                               query_parameters=query_parameters,
   1083                               content=content,
-> 1084                               media_type='application/json-patch+json')
   1085         return self._deserialize('WorkItem', response)
   1086 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\azure\devops\client.py in _send(self, http_method, location_id, version, route_values, query_parameters, content, media_type, accept_media_type, additional_headers)
     75                                                location_id=location_id,
     76                                                route_values=route_values,
---> 77                                                query_parameters=query_parameters)
     78         negotiated_version = self._negotiate_request_version(
     79             self._get_resource_location(location_id),

~\AppData\Local\Continuum\anaconda3\lib\site-packages\azure\devops\client.py in _create_request_message(self, http_method, location_id, route_values, query_parameters)
    130         logger.debug('Route template: %s', location.route_template)
    131         print(url)
--> 132         request = ClientRequest(method=http_method, url=self._client.format_url(url))
    133         if query_parameters:
    134             request.format_parameters(query_parameters)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\msrest\service_client.py in format_url(self, url, **kwargs)
    149         :param str url: The request URL to be formatted if necessary.
    150         """
--> 151         url = url.format(**kwargs)
    152         parsed = urlparse(url)
    153         if not parsed.scheme or not parsed.netloc:

KeyError: 'type'

**Comment by conhua** [comment]
@tedchamb

**Comment by borost1** [comment]
Same issue here, with the following stack trace:
`File "/Users/tboros/PycharmProjects/azuredevops/venv/lib/python3.7/site-packages/azure/devops/released/work_item_tracking/work_item_tracking_client.py", line 1085, in create_work_item
    media_type='application/json-patch+json')
  File "/Users/tboros/PycharmProjects/azuredevops/venv/lib/python3.7/site-packages/azure/devops/client.py", line 77, in _send
    query_parameters=query_parameters)
  File "/Users/tboros/PycharmProjects/azuredevops/venv/lib/python3.7/site-packages/azure/devops/client.py", line 129, in _create_request_message
    request = ClientRequest(method=http_method, url=self._client.format_url(url))
  File "/Users/tboros/PycharmProjects/azuredevops/venv/lib/python3.7/site-packages/msrest/service_client.py", line 152, in format_url
    url = url.format(**kwargs)
KeyError: 'type'
`
The service client receives the following: /project/_apis/wit/workItems/${type}

Really tried several things to fix this issue, yet none found.

@tedchamb

**Comment by tedchamb** [comment]
Thanks for reporting, fixed in #258

**Comment by tedchamb** [comment]
https://github.com/microsoft/azure-devops-python-api/releases/tag/5.1.0b2
