### ISSUE TITLE
AttributeError: 'TaskAgentClient' object has no attribute 'get_deployment_group'

### ISSUE THREAD

**Issue by gattjoe** [microsoft/azure-devops-python-api#276]
Hi,

I am using the latest version of the API (5.1.0b4) on Python 3.6 and am receiving the above error. I can see in https://github.com/microsoft/azure-devops-python-api/blob/dev/azure-devops/azure/devops/v5_1/task_agent/task_agent_client.py that there is indeed "Preview API" support for this endpoint; however, when I try to use it with the following code, I receive the error in the title.

def get_deployment_groups():
    deploymentgroups = []
    deployment_groups = task_agent_client.get_deployment_group(project="foobar")
    for group in deployment_groups:
        deploymentgroups.append(group)
    return deploymentgroups

Error: AttributeError: 'TaskAgentClient' object has no attribute 'get_deployment_group'

**Comment by tedchamb** [comment]
How are you getting the `task_agent_client`?  Since its preview you need to ask for it by version.
```
task_agent_client = connection.clients_v5_1.get_task_agent_client()
```

**Comment by gattjoe** [comment]
Hi, Thanks for the quick response. I was NOT asking for the client by version as you outlined above. Thank you for pointing this out to me.
