### ISSUE TITLE
Getting None Values for Secret Variables

### ISSUE THREAD

**Issue by pavan2004it** [microsoft/azure-devops-python-api#278]
I am using the below code snippet to pull all the release variables

personal_access_token = 'xyz'
organization_url = 'xyz'

credentials = BasicAuthentication('', personal_access_token)
connection = Connection(base_url=organization_url, creds=credentials)

release_client = connection.clients.get_release_client()
release_def = release_client.get_release_definitions(project='xyz')

release_def_var = release_client.get_release_definition(project='Integration', definition_id=def_id)

release_variable = {k: v.value for (k, v) in release_def_var.variables.items()}

print(release_variable)

How do i get the value of secret variable, since i am getting none as the value presently only for secret variables

**Comment by tedchamb** [comment]
I don't work on the team that owns this API, but the idea of a secret variable, is that you can set it, and the data is safe from anyone being able to view it.  If you can get it from a REST request, then it would be a security issue.  Tasks running in the context of the release will have access to the value.

**Comment by tedchamb** [comment]
@pavan2004it , I am going to close this issue.  If I didn't answer your questions, or you need more information from the team that owns this REST endpoint, you can ask your question here:

https://docs.microsoft.com/en-us/rest/api/azure/devops/release/?view=azure-devops-rest-5.1
