### ISSUE TITLE
Testsuite failure with PyPi sourcecode package

### ISSUE THREAD

**Issue by glaubitz** [microsoft/azure-devops-python-api#281]
Trying to run the testsuite of the PyPi package fails due to the missing module ```customer_intelligence_client```:

```
[   23s] ======================================================================
[   23s] ERROR: customer_intelligence_client (unittest.loader._FailedTest)
[   23s] ----------------------------------------------------------------------
[   23s] ImportError: Failed to import test module: customer_intelligence_client
[   23s] Traceback (most recent call last):
[   23s]   File "/usr/lib64/python3.7/unittest/loader.py", line 154, in loadTestsFromName
[   23s]     module = __import__(module_name)
[   23s]   File "/home/abuild/rpmbuild/BUILD/vsts-0.1.25/vsts/customer_intelligence/customer_intelligence_client.py", line 11, in <module>
[   23s]     from . import models
[   23s] ImportError: cannot import name 'models' from 'vsts.customer_intelligence' (/home/abuild/rpmbuild/BUILD/vsts-0.1.25/vsts/customer_intelligence/__init__.py)
[   23s] 
[   23s] 
[   23s] ----------------------------------------------------------------------
[   23s] Ran 1 test in 0.006s
```

The package was downloaded from https://pypi.org/project/vsts/#files

It can be reproduced with ```python3 setup.py build``` and ```python3 setup.py test```.

**Comment by tedchamb** [comment]
The `vsts` package has been renamed to `azure-devops`.  Can you try with the following package:

https://pypi.org/project/azure-devops/#files

**Comment by tedchamb** [comment]
@glaubitz , I am closing this issue, please reply back if you are having issues with the latest package under the new name, and I will reopen.

**Comment by glaubitz** [comment]
Do you know when ```azure-functions-devops-build``` is going to be updated to use ```azure-devops``` instead of ```vsts```? I just checked and the current 0.0.22 release still depends on ```vsts```.
