### ISSUE TITLE
Cannot inject private certificate for on-premises Azure DevOps Server

### ISSUE THREAD

**Issue by jwvanhollebeke** [microsoft/azure-devops-python-api#285]
Our organization currently uses an on-premises Azure DevOps Server with a self-signed certificate. We would like to trust that certificate in all calls to our on-premises server using the `azure-devops-python-api`.

I was not able to find a working example demonstrating how to do this, so we attempted the following:

```python
cert_file='/path/to/our/cert/file.pem'
connection = Connection(
            base_url='https://our-org-url/CollectionName',
            creds=credentials)

# Attempted each of the following:
connection._client.config.connection.verify = cert_file
connection._config.connection.verify = cert_file
connection._client.config.verify = cert_file
```

Unfortunately, all of these resulted in a **403** when calling our on-premises server. If you know the correct object property to set, that would be helpful. Setting this as a parameter in the constructor of the Connection object would have been even easier, if that were possible.

As a workaround, we set the `REQUESTS_CA_BUNDLE` env var to the path of our `.pem` file when calling our script. However, since the script also calls APIs with public trust, this means that we have had to aggregate our bundle to contain both our organization certificates and public certs. We would prefer a method where we can explicitly set the certificate trust chain for calls to our on-premises Azure DevOps Server and use the public trust chain for our other calls.

Thank you very much for this project, it has been very useful.

**Comment by tedchamb** [comment]
Thanks @jwvanhollebeke , have you checked with [msrest](https://github.com/Azure/msrest-for-python).  Any handling for client certificates is going to be done in their code.   If we are not exposing the proper msrest objects through this sdk to make to set the certs, please let us know.  Unfortunately I don't have a good environment set up to test this.

**Comment by tedchamb** [comment]
@jwvanhollebeke, is this a client certificate or a server certificate?

**Comment by tedchamb** [comment]
There was a related thread on this we had awhile back, but it looks like you are already working  around by following these steps:
https://github.com/Azure/azure-devops-cli-extension/issues/76

**Comment by jwvanhollebeke** [comment]
Thanks @tedchamb for your interest. You are correct, we are making a bundle containing all the server certs we trust similar to the workaround in your link. This is working fine for us. We would love an obvious, explicit way of setting the trust chain for calls to Azure DevOps in code, but we understand this may not be a priority. 

Based on your initial reply, I was thinking to also create an issue in the msrest project. Just going to poke around their codebase a bit more before I do that.
