### ISSUE TITLE
"The artifact type PipelineArtifact is not supported" with build_client.get_artifact_content_zip

### ISSUE THREAD

**Issue by aktzbn** [microsoft/azure-devops-python-api#286]
I'm trying to download pipeline artifact by means of `build_client.get_artifact_content_zip` method and receive error _"The artifact type PipelineArtifact is not supported"_.

Is there is a way to download pipeline artifact?

**Comment by tedchamb** [comment]
@aktzbn , I have contacted the team that owns this REST endpoint to get an official response for you.

**Comment by chweems** [comment]
@aktzbn which version of the client are you using?

**Comment by chweems** [comment]
Update: The bug has been identified in the API and a fix is currently under review.

**Comment by chweems** [comment]
The fix has been merged. You can expect it to reach you within the next week or so.

**Comment by tedchamb** [comment]
Thanks @chweems !  

Closing as this should be fixed now.  @aktzbn , let us know if you are still having issues.
