### ISSUE TITLE
Pipeline client is not accessible in the released package.

### ISSUE THREAD

**Issue by marian-craciunescu** [microsoft/azure-devops-python-api#287]
`connection.clients.get_pipelines_client()` it's not found since it is not in the  
`azure.devops.released.client_factory.py`

Should be exposed and added.

**Comment by tedchamb** [comment]
While most 5.1 APIs are released, there are some APIs that were introduced at version 5.1 or an earlier version, but were not ready to be released at the 5.1 release cutoff. These are still marked as -preview, and will most likely be released in 6.0. Each team is in control of when their APIs are considered released. Once that is done the python SDK, will automatically pick that up when we regenerate the clients.

For preview clients or methods, you need to get the client from the version specific factory:
`pipelines_client = connection.clients_v5_1.get_pipelines_client()`
