### ISSUE TITLE
GitClientBase.get_item_text always returns the file metadata

### ISSUE THREAD

**Issue by vbossica** [Microsoft/azure-devops-python-api#29]
To retrieve the content of a file, it is mandatory to send the 'text/plain' Accept header, otherwise the file metadata is always returned.

There are two issues:
1. the `VSSClient._send` hard codes `application/json` as Accept header
2. the generated `GitClientBase.get_item_text` must somehow pass `text/plain` as Accept header

**Comment by tedchamb** [comment]
We haven;t needed these methods yet, we will add them.

**Comment by reevery** [comment]
Similar for the get_item/blob_content/zip functions, they all return meta.

**Comment by vbossica** [comment]
@tedchamb any news on this one?

**Comment by tedchamb** [comment]
#160 should fix this issue.

**Comment by tedchamb** [comment]
https://github.com/Microsoft/azure-devops-python-api/releases/tag/0.1.23

**Comment by tedchamb** [comment]
@vbossica I am going to close this out.  Please let me know if you still have any issues downloading the content.
