### ISSUE TITLE
git_client.get_item() does not allow to get the file from a particular branch

### ISSUE THREAD

**Issue by marian-craciunescu** [microsoft/azure-devops-python-api#291]
If a file exists only in a particular branch but not on master, you can't use 
`    def get_item(self, repository_id, path, project=None, scope_path=None, recursion_level=None, include_content_metadata=None, latest_processed_change=None, download=None, version_descriptor=None, include_content=None, resolve_lfs=None):` to retrieve the version on that file

**Comment by tedchamb** [comment]
You can find documentation of this REST endpoint here:
https://docs.microsoft.com/en-us/rest/api/azure/devops/git/items/get?view=azure-devops-rest-5.1#gitversionoptions

You need to set the version_descriptor parameter, for example:

```
from azure.devops.connection import Connection
from azure.devops.v5_1.git.models import GitVersionDescriptor
from msrest.authentication import BasicAuthentication

import pprint

# Fill in with your personal access token and org URL
personal_access_token = 'xxx'
organization_url = 'https://dev.azure.com/myOrg'

credentials = BasicAuthentication('', personal_access_token)
connection = Connection(base_url=organization_url, creds=credentials)

git_client = connection.clients_v5_1.get_git_client()

version_descriptor = GitVersionDescriptor()
version_descriptor.version = "users/tedchamb/newbranch"
version_descriptor.version_type = 'branch'

item = git_client.get_item(project='MyProject', repository_id='MyRepository', path='/foo/bar.cs', version_descriptor=version_descriptor)
pprint.pprint(item.__dict__)
```
