### ISSUE TITLE
team_context problem

### ISSUE THREAD

**Issue by rilooth** [microsoft/azure-devops-python-api#295]
Hi,
I'm trying to use `get_boards()` method located in `get_work_client()`

first of all, I'm using `get_all_teams()` method located in `get_core_client()` to check `project_id`
after printing `project_id` I'm passing it to
`get = work_client.get_boards()`

but error appears

> if team_context.project_id:
> AttributeError: 'str' object has no attribute 'project_id'

what should be passed to the method then?

**Comment by tedchamb** [comment]
@rilooth , can you provide a code snippet?  Where are you getting team_context from?

**Comment by rilooth** [comment]
Hi @tedchamb 

```
credentials = BasicAuthentication('', personal_access_token)
connection = Connection(base_url=organization_url, creds=credentials)

core_client = connection.clients_v5_1.get_core_client()
get_all_teams = core_client.get_all_teams()

for i in get_all_teams:
    print(i.project_id)

```

I was trying to take `i.id`, `i.name`,` i.project_name` and pass it into team_context but still not working. 

I need it to extract what is written for work items like 'Acceptance Criteria' and 'Description' located in 'Boards' -> 'Work Items'. Maybe there is another way of extracting this?

**Comment by rilooth** [comment]
Hi @tedchamb 

I think I had a wrong thinking about the question.
The question is how to pass the team_context to the `get_boards()`

I was trying like this:

```
credentials = BasicAuthentication('', personal_access_token)
connection = Connection(base_url=organization_url, creds=credentials)

core_client = connection.clients_v5_1.get_core_client()
get_team = core_client.get_team("154f85b6-431a-43ed-b247-8446e5a18a76", "0fcf4689-2123-465f-88b0-de5e15c78b7a")

work_client = connection.clients_v5_1.get_work_client()
get = work_client.get_boards(get_team)

```
but now I have

> AttributeError: 'WebApiTeam' object has no attribute 'team_id'

Is there any workaround for this? 

btw. I'm trying to extract values for work items like 'Attributes' and 'Description' from Boards -> Work Items but I'm in the dark

**Comment by tedchamb** [comment]
[`get_team`](https://github.com/microsoft/azure-devops-python-api/blob/ff088658823d094f4cb3ba53e9ec864cd7b7415e/azure-devops/azure/devops/v5_1/core/core_client.py#L433)returns a [`WebApiTeam`](https://github.com/microsoft/azure-devops-python-api/blob/ff088658823d094f4cb3ba53e9ec864cd7b7415e/azure-devops/azure/devops/v5_1/core/models.py#L884) object.  [`get_boards`](https://github.com/microsoft/azure-devops-python-api/blob/ff088658823d094f4cb3ba53e9ec864cd7b7415e/azure-devops/azure/devops/v5_1/work/work_client.py#L250) takes a [`TeamContext`](https://github.com/microsoft/azure-devops-python-api/blob/ff088658823d094f4cb3ba53e9ec864cd7b7415e/azure-devops/azure/devops/v5_1/work/models.py#L992) object.  You will need to convert the `WebApiTeam` object into a `TeamContext` object, by doing something like this:

```
team_context = TeamContext()
team_context.project_id = get_team.project_id
team_context.team_id = get_team.id

get = work_client.get_boards(team_context)
```

or since you already know the ids, you can skip the `get_team` call and do this:
```
team_context = TeamContext()
team_context.project_id = "154f85b6-431a-43ed-b247-8446e5a18a76"
team_context.team_id = "0fcf4689-2123-465f-88b0-de5e15c78b7a"

get = work_client.get_boards(team_context)
```

**Comment by rilooth** [comment]
Hi @tedchamb 

thank you for your response. That worked for me. 
Do you have any idea if there is any method I can get text under work items fields like "Acceptance Criteria" or "Description"?

**Comment by tedchamb** [comment]
[`get_work_item`](https://github.com/microsoft/azure-devops-python-api/blob/21f891ab9dc3e2927ca884ccc62a13e3899c5295/azure-devops/azure/devops/v5_1/work_item_tracking/work_item_tracking_client.py#L1666)

REST doc here:
https://docs.microsoft.com/en-us/rest/api/azure/devops/wit/work%20items/get%20work%20item?view=azure-devops-rest-5.1

**Comment by kishantec** [comment]
Hi  @tedchamb
           get_boards attribute is a part of get_work_client() function. Could you confirm   get_work_item attribute is a part of which source function. Im looking to get the Work Item ID, Name and the State(active/closed) of a Work Item in Azure Devops. I get error when i try this.

 for board in wit_client.get_boards(team_ctx):
            pprint.pprint("Board ID " + board.id)
            pprint.pprint("Board Name " + board.name)
            print(board.get_work_item(projects.id))
The Error is BoardReferenceObject has no attribute get_work_item
