### ISSUE TITLE
Client for API version 6.0

### ISSUE THREAD

**Issue by atbagga** [microsoft/azure-devops-python-api#302]
Some of the newer functionality is release in the new APIs e.g. [PR merge policy options](https://docs.microsoft.com/en-us/rest/api/azure/devops/git/pull%20requests/update?view=azure-devops-rest-6.0#gitpullrequestmergestrategy).

**Comment by tedchamb** [comment]
I'll try and put out a 6.0 preview version this week.

**Comment by corbyjames** [comment]
Subscribed as we are also looking for the v6 version.

**Comment by tedchamb** [comment]
Commit: https://github.com/microsoft/azure-devops-python-api/pull/304/commits/9a04304a3119c2279a424422cef4ea12a1615e96

Release: [6.0.0b1](https://github.com/microsoft/azure-devops-python-api/releases/tag/6.0.0b1)
