### ISSUE TITLE
Capacity per day as integer only

### ISSUE THREAD

**Issue by RK159** [microsoft/azure-devops-python-api#305]
In v5_1/work/models.py

`
class Activity(Model):
    """Activity.

    :param capacity_per_day:
    :type capacity_per_day: int
    :param name:
    :type name: str
    """

    _attribute_map = {
        'capacity_per_day': {'key': 'capacityPerDay', 'type': 'int'},
        'name': {'key': 'name', 'type': 'str'}
    }

    def __init__(self, capacity_per_day=None, name=None):
        super(Activity, self).__init__()
        self.capacity_per_day = capacity_per_day
        self.name = name

`

 the type of the parameter capacity_per_day is 'int', but the user could fill that field with a float.

For instance with a 10 days iteration, if the user fills "4.9" in capacity per day, and that we want to use the api to calculate the total capacity for the iteration, the results from the api will be 40 instead of 49

Is there a way to change that?

**Comment by tedchamb** [comment]
#308

**Comment by tedchamb** [comment]
@RK159 thanks for reporting this issue.

The fix is in the following releases:
https://github.com/microsoft/azure-devops-python-api/releases/tag/6.0.0b2
https://github.com/microsoft/azure-devops-python-api/releases/tag/5.1.0b7

**Comment by RK159** [comment]
Thanks for the quick response @tedchamb that helps a lot!
