### ISSUE TITLE
Is there a way to get and update the description of a work item?

### ISSUE THREAD

**Issue by chantisnake** [microsoft/azure-devops-python-api#311]
I see in the `WorkItemTrackingClient` there is `create_work_item`, `update_work_item` API. But neither of them can specify the description of the work item and the acceptance criteria.

Is there a way to create a work item with specific description and acceptance criteria?

**Comment by BBDXF** [comment]
you can ref [issue](https://github.com/microsoft/azure-devops-python-api/issues/226), and code [code](https://github.com/Azure/azure-devops-cli-extension/blob/768aff8971aad2e194fa26d796d47b3a67292b4e/azure-devops/azext_devops/dev/boards/work_item.py#L24)

**Comment by tedchamb** [comment]
Thanks for responding to this @BBDXF !
