### ISSUE TITLE
OPTIONS not functional - how to proceed?

### ISSUE THREAD

**Issue by silvio** [microsoft/azure-devops-python-api#325]
OPTIONS not functional - how to proceed?

I'm using a devops-server which obviously doesn't support "OPTIONS" as http-get method. When I try to access the server via `curl`, I get the following behavior...

~~~text
curl -I --request GET --url 'https://SERVER/collectionkfurt/automotivekfurt/_apis' --header 'authorization: Basic TOKENB64'
HTTP/2 200
[...]
~~~

In contrast.

~~~text
curl -I --request OPTIONS --url 'https://SERVER/collectionkfurt/automotivekfurt/_apis' --header 'authorization: Basic TOKENB64'
HTTP/2 404
[...]
~~~

I see that in the `client.py` module OPTIONS is used to establish a first connection. **Is there a way around this?**

For testing I use the following code:

~~~python
ORGURL = "https://SERVER/collectionkfurt/automotivekfurt"
credential = BasicAuthentication(USERNAME, PAT)
connection = Connection(base_url=ORGURL, creds=self.credential)
core = self.connection.clients.get_core_client();
~~~

The error occurs at the line `self.connection.clients.get_core_client();`, with ...

~~~text
raise AzureDevOpsClientRequestError(full_message_format.format(error_message=error_message,                                          
azure.devops.exceptions.AzureDevOpsClientRequestError: Page not found.  Operation returned a 404 status code. 
~~~

**Comment by tedchamb** [comment]
Try:
```python
ORGURL = "https://SERVER/collectionkfurt"
```

**Comment by silvio** [comment]
Hi @tedchamb ,

> Try:
> 
> ```python
> ORGURL = "https://SERVER/collectionkfurt"
> ```

Yeees great - its working. But why? I didn't see any OPTIONS request anymore.

**Comment by tedchamb** [comment]
If the `OPTIONS` call wasn't made, that means you have the options data already cached for that url.  Once the cache expires it will make the `OPTIONS` call again.  

The cache file is in the following location.
```python
os.path.expanduser(os.path.join('~', '.azure-devops', 'python-sdk', 'cache')
```
You can delete the cache folder or file if you want to see the `OPTIONS` call made again.

**Comment by silvio** [comment]
Thanks for your help. Its working fine now.
