### ISSUE TITLE
Trying to use get_attachment_content in RESTful API

### ISSUE THREAD

**Issue by jeffpohlmeyer** [microsoft/azure-devops-python-api#330]
I have a site for which I'm building a customer comment/feedback section that I am hooking into DevOps to almost use as a SaaS so that we don't have to manually add bugs to DevOps.  I've built functionality where a user can upload a file, but I want to build functionality to allow the user to again view the file that s/he uploaded.  When I try to invoke get_attachment_content for a given ID I get a type <generator object RequestsClientResponse.stream_download at ...>  How am I able to grab the content from said generator in order to convert it to a file to send for download?  Even if I'm able to get the binary data from the generator it would be helpful because I can then convert the binary myself.

**Comment by tedchamb** [comment]
Here is an example of doing a file download.  In this example we download all attachments found on work items from the given wiql query:

```python
def download_callback(chunk, response):
    pprint.pprint('Downloaded chunk of size: ' + str(len(chunk)))


wit_client = connection.clients.get_work_item_tracking_client()

wiql = Wiql()
wiql.query = "Select [System.Id], [System.Title], [System.State] From WorkItems Where [System.WorkItemType] = 'Task'"

wiql_results = wit_client.query_by_wiql(wiql, top=100).work_items
if wiql_results:
    pprint.pprint(wiql_results)
    work_items = (
        wit_client.get_work_item(int(res.id), expand='Relations') for res in wiql_results
    )
    for work_item in work_items:
        pprint.pprint(work_item)
        if work_item.relations is not None:
            for relation in work_item.relations:
                if relation.rel == 'AttachedFile':
                    response = wit_client.get_attachment_zip(relation.url.split('/')[-1],
                                                             download=True,
                                                             callback=download_callback)
                    with open(relation.attributes['name'], 'wb') as f:
                        for x in response:
                            f.write(x)
```

**Comment by JVP3122** [comment]
Sorry I forgot to reply.  This helped me out a lot.  Thank you very much.

**Comment by jeffpohlmeyer** [comment]
I'm going to re-open this quickly as I had to drop what I was doing with this for a bit.

I'm using this in a Django Rest Framework API setting and while this code does exactly what it should, which is grab all attachments and write them to the disk with their associated name, what I'm trying to do is convert the generator into an HttpResponse object.  I've been looking around on StackOverflow a bit and everything that I've seen about serving files as Django responses have to do with opening local files and serving them.

I hate to ask this here, and if you don't know I'm happy to close it again, but is there any chance you know how I would go about serving the downloaded content directly in the response?
