### ISSUE TITLE
Wait time till operations successfully completed

### ISSUE THREAD

**Issue by mo-saeed** [microsoft/azure-devops-python-api#352]
Hi,

I am trying to use queue_create_project to create a new project then directly create a team in the project using `create_team` method, sometimes `create_team` fails with Project doesn't exist exception. any trick how to make `create_project` function waits till the project is successfully created

**Comment by tedchamb** [comment]
There is a good example of how to do this in the `azure-dvops-cli-extension`, which uses a copy of this sdk:

Create Project
https://github.com/Azure/azure-devops-cli-extension/blob/master/azure-devops/azext_devops/dev/team/project.py#L21

The wait logic is here:
https://github.com/Azure/azure-devops-cli-extension/blob/683ff8a124ac58ff88c98304fc4cffc048d8620c/azure-devops/azext_devops/dev/common/operations.py#L11
