### ISSUE TITLE
Meet `FileExistsError` while importing vsts package occasionally

### ISSUE THREAD

**Issue by arrownj** [microsoft/azure-devops-python-api#354]
Hi Team,

We run some tests in ADO and meet below error:

> ____ ERROR collecting tests/latest/test_devops_build_commands_thru_mock.py _____
/usr/local/Cellar/azure-cli/2.10.1/libexec/lib/python3.8/site-packages/azure/cli/command_modules/appservice/tests/latest/test_devops_build_commands_thru_mock.py:10: in <module>
    from azure.cli.command_modules.appservice.azure_devops_build_interactive import (
/usr/local/Cellar/azure-cli/2.10.1/libexec/lib/python3.8/site-packages/azure/cli/command_modules/appservice/azure_devops_build_interactive.py:31: in <module>
    from .azure_devops_build_provider import AzureDevopsBuildProvider
/usr/local/Cellar/azure-cli/2.10.1/libexec/lib/python3.8/site-packages/azure/cli/command_modules/appservice/azure_devops_build_provider.py:7: in <module>
    from azure_functions_devops_build.project.project_manager import ProjectManager
/usr/local/Cellar/azure-cli/2.10.1/libexec/lib/python3.8/site-packages/azure_functions_devops_build/project/project_manager.py:14: in <module>
    from ..base.base_manager import BaseManager
/usr/local/Cellar/azure-cli/2.10.1/libexec/lib/python3.8/site-packages/azure_functions_devops_build/base/base_manager.py:6: in <module>
    from vsts.vss_connection import VssConnection
/usr/local/Cellar/azure-cli/2.10.1/libexec/lib/python3.8/site-packages/vsts/vss_connection.py:9: in <module>
    from ._file_cache import RESOURCE_CACHE as RESOURCE_FILE_CACHE
/usr/local/Cellar/azure-cli/2.10.1/libexec/lib/python3.8/site-packages/vsts/_file_cache.py:122: in <module>
    DEFAULT_CACHE_DIR = get_cache_dir()
/usr/local/Cellar/azure-cli/2.10.1/libexec/lib/python3.8/site-packages/vsts/_file_cache.py:117: in get_cache_dir
    os.makedirs(vsts_cache_dir)
/usr/local/Cellar/azure-cli/2.10.1/libexec/lib/python3.8/os.py:223: in makedirs
    mkdir(name, mode)
E   FileExistsError: [Errno 17] File exists: '/Users/runner/.vsts/python-sdk/cache'

After check the source code, we found the error happens in [this](https://github.com/microsoft/azure-devops-python-api/blob/3838e91d662dba1f77b43ad560ca23c1cb7e84e8/azure-devops/azure/devops/_file_cache.py#L117) line.

It seems to have something to do with parallel running. Can anyone help with this ?

**Comment by tedchamb** [comment]
fixed in #356 

This can happen if the cache directory doesn't exists and two threads try to create it at the same time.  

You are using the very old package `vsts`.  The fix is in `azure-devops`.  To work around the issue you can do one of the following:
1. create the cache directory before you run your tests:  `~/.vsts/python-sdk/'cache` or in your case `/Users/runner/.vsts/python-sdk/cache`
2. set the `VSTS_CACHE_DIR` env var to a folder path that already exists.
