### ISSUE TITLE
Add support to API version 6.1

### ISSUE THREAD

**Issue by mo-saeed** [microsoft/azure-devops-python-api#371]
Hello, azure devops api version 6.1 is available https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-6.1, would be great to include it.

**Comment by nechvatalp** [comment]
Hello, we took our time but a new version is finally out with support for API 7.0 and 7.1, all APIs which were introduced in 6.1 should be included.
