### ISSUE TITLE
msrest.exceptions.DeserializationError: Unable to deserialize to object: type, KeyError: ' key: int; value: str '

### ISSUE THREAD

**Issue by aravindtv** [microsoft/azure-devops-python-api#377]
I have written a python script to change the access level of users from basic to stakeholder by using the python library azure-devops, in that the specific function **update_user_entitlement( body, user_id )** , till last month script was working perfectly fine, suddenly I am facing below said issue

	  return [self.deserialize_data(a, iter_type) for a in attr]
	  File "/opt/hostedtoolcache/Python/3.9.2/x64/lib/python3.9/site-packages/msrest/serialization.py", line 1631, in deserialize_data
		return self._deserialize(obj_type, data)
	  File "/opt/hostedtoolcache/Python/3.9.2/x64/lib/python3.9/site-packages/msrest/serialization.py", line 1446, in _deserialize
		raise_with_traceback(DeserializationError, msg, err)
	  File "/opt/hostedtoolcache/Python/3.9.2/x64/lib/python3.9/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
		raise error.with_traceback(exc_traceback)
	  File "/opt/hostedtoolcache/Python/3.9.2/x64/lib/python3.9/site-packages/msrest/serialization.py", line 1442, in _deserialize
		value = self.deserialize_data(raw_value, attr_desc['type'])
	  File "/opt/hostedtoolcache/Python/3.9.2/x64/lib/python3.9/site-packages/msrest/serialization.py", line 1618, in deserialize_data
		return self.deserialize_type[iter_type](data, data_type[1:-1])
	  File "/opt/hostedtoolcache/Python/3.9.2/x64/lib/python3.9/site-packages/msrest/serialization.py", line 1649, in deserialize_iter
		return [self.deserialize_data(a, iter_type) for a in attr]
	  File "/opt/hostedtoolcache/Python/3.9.2/x64/lib/python3.9/site-packages/msrest/serialization.py", line 1649, in <listcomp>
		return [self.deserialize_data(a, iter_type) for a in attr]
	  File "/opt/hostedtoolcache/Python/3.9.2/x64/lib/python3.9/site-packages/msrest/serialization.py", line 1618, in deserialize_data
		return self.deserialize_type[iter_type](data, data_type[1:-1])
	  File "/opt/hostedtoolcache/Python/3.9.2/x64/lib/python3.9/site-packages/msrest/serialization.py", line 1665, in deserialize_dict
		return {k: self.deserialize_data(v, dict_type) for k, v in attr.items()}
	  File "/opt/hostedtoolcache/Python/3.9.2/x64/lib/python3.9/site-packages/msrest/serialization.py", line 1665, in <dictcomp>
		return {k: self.deserialize_data(v, dict_type) for k, v in attr.items()}
	  File "/opt/hostedtoolcache/Python/3.9.2/x64/lib/python3.9/site-packages/msrest/serialization.py", line 1620, in deserialize_data
		obj_type = self.dependencies[data_type]
	msrest.exceptions.DeserializationError: Unable to deserialize to object: type, KeyError: ' key: int; value: str '

**My Python script**

    from azure.devops.connection import Connection
    from dateutil.relativedelta import relativedelta
    from msrest.authentication import BasicAuthentication
    from datetime import *
    
    import datetime
    import os
    
    # Fill in with your personal access token and org URL
    personal_access_token = 'some_PAT'
    organization_url = 'https://dev.azure.com/some_organization'
    
    # Create a connection to the org
    credentials = BasicAuthentication('some_organization', personal_access_token)
    connection = Connection(base_url=organization_url, creds=credentials)
    
    # Get a client (the "member entitlement management" client provides access to users, accessTypes, lastAccessedDate etc)
    member_entitlement_management_client = connection.clients_v6_0.get_member_entitlement_management_client()
    
    # Get the first page of users
    get_users_response = member_entitlement_management_client.search_user_entitlements()
    # print(get_users_response)
    
    with open("usersList2.txt", "w") as outF:
      with open("usersList2_email.txt", "w") as out_email:
        while get_users_response is not None:
            Never = datetime.datetime(1, 1, 1, 0, 0)
            three_months = date.today() - relativedelta(months=+3)
            domain = "@amadeus.com"
            continuation_token = get_users_response.additional_properties["continuationToken"]
            for user in get_users_response.members:
                # List all the users who are inactive from past 3 months
                if (user.last_accessed_date.date() < three_months):  # and user.last_accessed_date.date() != Never.date()):
                    if domain in user.user.mail_address:
                        #print(user.user.display_name)
                        outF.write(user.id)
                        outF.write("\n")
                        out_email.write(user.user.mail_address)
                        out_email.write("\n")
    
            if continuation_token is not None and continuation_token != "":
                # Get the next page of users
                get_users_response = member_entitlement_management_client.search_user_entitlements(
                    continuation_token=continuation_token)
            else:
                # All users have been retrieved
                get_users_response = None

    with open('usersList1.txt', 'r') as file1:
        with open('usersList2.txt', 'r') as file2:
            same = set(file1).intersection(file2)

    same.discard('\n')
    
    with open('same.txt', 'w') as file_out:
        for line in same:
            file_out.write(line)
    
    with open('same.txt', 'r') as f:
        content = f.readlines()
    content = [x.strip() for x in content]
    print(content)
    for user_id in content:
        requestBody = [
                     {
                      "from": "",
                      "op": "replace",
                      "path": "/accessLevel",
                      "value": {
                        "accountLicenseType": "stakeholder",
                        "licensingSource": "account"
                      }
                     }
                    ]
        #changing users access from basic to stakholder
        response = member_entitlement_management_client.update_user_entitlement(requestBody, user_id)
        print(response)
    

In the above code, **content** is a list of user ID's
    
Could anyone please help me with this issue?
Please let me know if you need more information.
    
Thanks in advance
    
Regards,
Aravind

**Comment by aravindtv** [comment]
Hi @tedchamb ,

Any updates on this issue. Could you please help me here?
I observed it is an intermittent issue, especially with this call. member_entitlement_management_client.update_user_entitlement()

**Comment by tedchamb** [comment]
Adding @goflores, who is the current maintainer of the sdk. 

@aravindtv, can you take a fiddler trace, and see what the json response is when it can't deserialize?

**Comment by aravindtv** [comment]
> Adding @goflores, who is the current maintainer of the sdk.
> 
> @aravindtv, can you take a fiddler trace, and see what the json response is when it can't deserialize?

**Comment by aravindtv** [comment]
Hi @tedchamb ,

I found the root cause of the issue.
When there is a User in the organization without the direct assignment (means License Source as Group Rule) then the library throws the error saying it cannot deserialize).

![image](https://user-images.githubusercontent.com/55797956/115138520-56d8b980-a04a-11eb-9229-2cfed087fb0f.png)

There is no error if there are only users with direct assignments (Direct as License source).

How can this be solved with the same library call? (changing access of the users with both Direct and Group Rule as License Source).

Please do the needful

**Comment by aravindtv** [comment]
Hi @tedchamb ,
I got to know the issue. I am trying to change the access level of the user whose license is inherited from Group Rule.
I will close this issue, as it is nt valid.

![image](https://user-images.githubusercontent.com/55797956/115190004-03777180-a105-11eb-8614-5b4a9f540bae.png)
