### ISSUE TITLE
How to download Attachment from Test Steps?

### ISSUE THREAD

**Issue by Thirumal-Palwai** [microsoft/azure-devops-python-api#424]
I can get a list of attachments from this [API](https://docs.microsoft.com/en-us/rest/api/azure/devops/test/attachments/get-test-result-attachments?view=azure-devops-rest-6.0&tabs=HTTP)

I can also download the attachments from [API](https://docs.microsoft.com/en-us/rest/api/azure/devops/test/attachments/get-test-run-attachment-zip?view=azure-devops-rest-6.0)

But I did not find a document to download attachments from Test Steps.

Can you help us in finding the appropriate document?

Thank you.

**Comment by vibhash1083** [comment]
Which attachment are you looking for? Attachments added inline to test step while creating a test case?

**Comment by vchandram** [comment]
Which attachments are you looking for? Attachments added inline to a step while creating a test case or attachment added from attachment column while creating a test case.
