### ISSUE TITLE
How can I fetch comments with specified version of the work_item_tracking_client

### ISSUE THREAD

**Issue by Can-Yilmaz** [microsoft/azure-devops-python-api#426]
I need to fetch comments of a specified workitem of a azure devops project. However, although there is a method called `get_comments()` in 

> /venv/Lib/site-packages/azure/devops/v5_1/work_item_tracking/work_item_tracking_client.py

I cannot access to that client. Instead, I get the workitem tracking client that defined at 

> /venv/Lib/site-packages/azure/devops/released/work_item_tracking/work_item_tracking_client.py

which doesn't include `get_comments() ` method, I couldn't find where can I choose the version of the client.

The method;

```
def workitems(self, project=None, repository=None, from_date=None):
        """Fetch the work items from azure devops for a project"""
        wit_client = self.connection.clients.get_work_item_tracking_client()
        if from_date is not None and repository is not None:
            date_param = f"""where [System.CreatedDate] >= '{from_date}'"""
            repo_param = f"""AND [System.AreaPath] = '{repository}'"""
        else:
            date_param = ""
            repo_param = ""
        wiql = Wiql(
            query=f"""
select [System.Id],
[System.WorkItemType],
[System.Title],
[System.State],
[System.AreaPath],
[System.IterationPath],
[System.Tags],
[System.TeamProject]
from WorkItems
{date_param}
{repo_param}
order by [System.Id] desc"""
        )
        if project is not None:
            wiql_results = wit_client.query_by_wiql(wiql).work_items
        else:
            team_context = TeamContext(project=project)
            wiql_results = wit_client.query_by_wiql(
                wiql, team_context=team_context
            ).work_items
        if wiql_results is not None:
            for work_item in wiql_results:
                wit_with_updates_and_comments = wit_client.get_work_item(int(work_item.id),
                                                                         expand="Relations").as_dict()
                updates = [x.as_dict() for x in wit_client.get_updates(int(work_item.id))]
                wit_with_updates_and_comments["updates"] = updates
                comments = wit_client.get_comments(project=project, work_item_id=(int(work_item.id)))
                wit_with_updates_and_comments["comments"] = comments
                yield wit_with_updates_and_comments
```

When the method is runned an exception emerges stating that 
`comments = wit_client.get_comments(project=project, work_item_id=(int(work_item.id)))
AttributeError: 'WorkItemTrackingClient' object has no attribute 'get_comments'`

Thank you.

**Comment by Mikaciu** [comment]
Hello, 

Did you try using the 6.0 version of the work_item_tracking package ?

The (https://github.com/microsoft/azure-devops-python-api/blob/dev/azure-devops/azure/devops/v6_0/work_item_tracking/work_item_tracking_client.py#L379)[`get_comments` method] is present in this version, but is not in the `released` package.

**Comment by Can-Yilmaz** [comment]
Thank you sir.
