### ISSUE TITLE
Repository is outdated

### ISSUE THREAD

**Issue by fbrodrigorezino** [microsoft/azure-devops-python-api#429]
When will we have updates in this repository? 
We already have other API versions, python versions, and so one, and no movement here.

**Comment by tonybaloney** [comment]
I'm picking up this repo to try and get it up to scratch. Python versions are being updated, dev now works up to 3.11.

Currently trying to track down the generator that was last used for the client code, the API is now at version 7.1, this current build is for v6.0 (preview).

**Comment by nechvatalp** [comment]
We released a new version with support for the latest API versions, hopefully going forward this repository will be more alive than for the past few years.
