### ISSUE TITLE
No module named 'azure.devops.v7_0.git.git_client'

### ISSUE THREAD

**Issue by JPK314** [microsoft/azure-devops-python-api#455]
Repro: call Connection('', creds=cred).clients.get_git_client(). The trace starts in azure/devops/v7_0/git/__init__.py on the line "from .git_client import GitClient"

**Comment by JPK314** [comment]
Closed as duplicate of [453](https://github.com/microsoft/azure-devops-python-api/issues/453#issue-1674735502`). Installed azure-devops==5.1.0b8 and can use client successfully.

**Comment by yishuiliunian** [comment]
I have created a PR to fix it. But it is waiting for approval.

https://github.com/microsoft/azure-devops-python-api/pull/456
