### ISSUE TITLE
Sample code snippet

### ISSUE THREAD

**Issue by tlnarayana** [Microsoft/azure-devops-python-api#89]
Hi ,
Thanks to excellent api.

Provided example - how to get team_projects using basic authentication is good.
But is not enough for beginners.

Could you please provide more code snippets for
--> How to navigate from team project to TestPlan and its test runs
--> How to update test run outcome/results

Basically - we are looking for
--> Find test plan
--> Find latest Test run
--> Update test run results w.r.t Functional Test cases executed in our regression test suite in jenkins ( this is Python Robot selenium Framework for Functional Test case automation )

Please provide documentation/example code snippets or any pointers.

Looking forward for your favorable reply.

Regards,
LnT

**Comment by MartinCalderon** [comment]
Hello, 

Would be possible to help. I'm trying to understand from where Team Context comes from. For example the function in the vsts-python-api/vsts/vsts/work/v4_1/work_client.py

def get_backlogs(self, team_context):
        """GetBacklogs.
        [Preview API] List all backlog levels
        :param :class:`<TeamContext> <work.v4_1.models.TeamContext>` team_context: The team context for the operation
        :rtype: [BacklogLevelConfiguration]
        """
---

Thank you in advance, this is a very nice SDK.

**Comment by jfthuong** [comment]
@all 

There are actually some samples in this repository: https://github.com/Microsoft/azure-devops-python-samples

... But they are (currently) rather limited and for example do not address how to use WIQL queries (or similar queries other than just getting information on workitems by ID).

**Comment by tedchamb** [comment]
You can also find real usage by looking in the [vsts-cli](https://github.com/Microsoft/vsts-cli) repo under [common_modules](https://github.com/Microsoft/vsts-cli/tree/dev/src/common_modules).

@MartinCalderon, sorry I am just seeing your question now.  the teamcontext is used to scope the request to a project or a specific team within a project.  The teamcontext class is auto-generated from the c# binaries.  In c#, `project` would be a string and `project_id` would be of type guid, and you would set one or the other.  In python having two separate fields is confusing because they are both strings.  In the 5.0 version of our python sdk, we should probably depart from matching the c# clients, and just have two separate string parameters.

```
class TeamContext(Model):
    """TeamContext.

    :param project: The team project Id or name.  Ignored if ProjectId is set.
    :type project: str
    :param project_id: The Team Project ID.  Required if Project is not set.
    :type project_id: str
    :param team: The Team Id or name.  Ignored if TeamId is set.
    :type team: str
    :param team_id: The Team Id
    :type team_id: str
    """

    _attribute_map = {
        'project': {'key': 'project', 'type': 'str'},
        'project_id': {'key': 'projectId', 'type': 'str'},
        'team': {'key': 'team', 'type': 'str'},
        'team_id': {'key': 'teamId', 'type': 'str'}
    }

    def __init__(self, project=None, project_id=None, team=None, team_id=None):
        super(TeamContext, self).__init__()
        self.project = project
        self.project_id = project_id
        self.team = team
        self.team_id = team_id
```

You can see in the client method that the two fields are interchangeable in python, and we only set one project and one team in the request.
```
        if team_context is not None:
            if team_context.project_id:
                project = team_context.project_id
            else:
                project = team_context.project
            if team_context.team_id:
                team = team_context.team_id
            else:
                team = team_context.team
```

**Comment by jfthuong** [comment]
@tlnarayana 

Please have a look at the amazing analysis done by christopherthompson81 about the client "magic strings" and the functions available in this issue: https://github.com/Microsoft/azure-devops-python-api/issues/132

Basically, you need to:
1. Connect to the proper client and "guessing" its magic name by looking at the folders.

In my case (API version 4.1), I have the following magic strings:
* **Workitems**: `"vsts.work_item_tracking.v4_1.work_item_tracking_client.WorkItemTrackingClient"`
* **Test Runs/Results**: `"vsts.test.v4_1.test_client.TestClient"`

2. Open "test_client.py" to see all functions available for test results and find the one that best suits your need.

I am currently trying to do exactly the same thing as you do (and struggling like you apparently do) and I came up with the following solution: https://stackoverflow.com/a/53074966/1603480

Hope it can help.

**Comment by tedchamb** [comment]
Closing this issue, please let me know if you are still having issues.
